#!/bin/bash
# Sign the deployed VoiceHarnessClient.app with the iCloud entitlement so
# CKContainer.default() works and identity federation uses the iCloud key.
#
# Prereqs:
#   - Apple Development signing identity (security find-identity -v -p codesigning)
#   - A macOS provisioning profile for the app containing the iCloud container
#     entitlement (generated by Xcode for this app id; place it at
#     clients/macos/voice-harness-client/VoiceHarnessClient.provisionprofile).
#     Generate once in Xcode: target VoiceHarnessClient (macOS) → Signing &
#     Capabilities → iCloud (CloudKit, container iCloud.wtf.geese.voice-harness),
#     then export the profile (Xcode will keep it in
#     ~/Library/Developer/Xcode/UserData/Provisioning Profiles, or use
#     `xcrun xcodebuild -downloadProvisioningProfiles -bundle-id com.zippystation.voice-harness-client`).
#
# Usage: scripts/sign-macos-bundle.sh
set -euo pipefail

APP_DIR="${APP_DIR:-/Applications/VoiceHarnessClient.app}"
ENTITLEMENTS="$(dirname "$0")/../clients/macos/voice-harness-client/Entitlements.plist"
PROFILE="$(dirname "$0")/../clients/macos/voice-harness-client/VoiceHarnessClient.provisionprofile"
IDENTITY="${IDENTITY:-Apple Development: trevo.nielsen@protonmail.com (73F57295L8)}"
BUNDLE_ID="com.zippystation.voice-harness-client"

# The app must not run while being re-signed.
pkill -f VoiceHarnessClient.app 2>/dev/null || true
sleep 1

# Embed the provisioning profile so the system (and SecTask) can see the
# entitlements granted to this bundle id.
if [[ -f "$PROFILE" ]]; then
  cp "$PROFILE" "$APP_DIR/Contents/embedded.provisionprofile"
else
  echo "NOTE: no provisioning profile at $PROFILE — skipping profile embed."
  echo "      CKContainer will still refuse to construct without the profile"
  echo "      registered with the entitlement (macOS checks both)."
fi

codesign --force --sign "$IDENTITY" \
  --entitlements "$ENTITLEMENTS" \
  --options runtime \
  --bundle-version-requirement=1 \
  "$APP_DIR"

# Verify: signature valid + entitlements actually attached.
codesign --verify --deep --strict "$APP_DIR"
codesign -dv --entitlements :- "$APP_DIR" | grep -q "icloud-container-identifiers" || {
  echo "ERROR: iCloud entitlement missing after signing" >&2
  exit 1
}

echo "OK: signed with iCloud entitlement."
open "$APP_DIR"
